
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_demo_june_development
test:
  <<: *default
  database: rails_demo_june_test

production:
  <<: *default
  database: rails_demo_june_production
  username: rails_demo_june
  password: <%= ENV['RAILS_DEMO_JUNE_DATABASE_PASSWORD'] %>
